### ISSUE TITLE
Add dbcompat consideration?

### ISSUE THREAD

**Issue by nabeelderhem** [Microsoft/MCW-Windows-Server-and-SQL-Server-2008-R2-End-of-Support-Planning#13]
I noticed we're missing information about DBCompat and our slight change in focus to certify to a compatibility level rather than a specific engine version and/or platform (on-prem vs. Azure).  More info here: https://aka.ms/dbcompat

**Comment by paulopsgility** [comment]
Do you have any supporting documentation for this statement: "our slight change in focus to certify to a compatibility level rather than a specific engine version and/or platform" or were you just referring to how Azure SQL Databases are versioned by compatibility level and underlying server versions are obfuscated? The documentation you pointed out is about database compatibility levels which has not changed in eons. Even the best practices around compatibility levels hasn't changed. I am just not seeing anything to indicate that there is an official change in positioning or supportability from Microsoft around this, it looks to be the same as it has always been. 

This workshop is about end of life of the boxed products and the support, upgrade options, offerings and tools that can help you maintain supportability. While database compatibility level will certainly come into play during an upgrade, in general, all of the tools that touch the database in this workshop support at least compatibility level 100 or higher and I don't want to go off in the weeds of describing every potential issue that one of these tools might flag (such as database compatibility level). I think that an in depth discussion around database compatibility level would be more appropriate for a dedicated MCW on database upgrade where we would have more time to dive into many of the common technical issues and remediations.

**Comment by paulopsgility** [comment]
I am closing this as it applies to SQL Server upgrades specifically and not necessarily end of support planning. In other words, this topic belongs in a more detailed workshop specific to database version upgrades (preferably something with a lab to demonstrate the significance of this).
